export const FERRAVINE_CARE_CUES = Object.freeze({
  "intake-unfurl": { id: "intake-unfurl", caption: "Ferravine's intake slit unfurls with a soft muscular ratchet." },
  "throat-ready": { id: "throat-ready", caption: "Her fuel throat opens; valves test the seal." },
  "fuel-swallow": { id: "fuel-swallow", caption: "The pump pulse settles into a deep swallowing rhythm." },
  "taste-pause": { id: "taste-pause", caption: "The throat stills to taste the first mouthful." },
  "contamination-clamp": { id: "contamination-clamp", caption: "The intake clamps shut." },
  "reverse-purge": { id: "reverse-purge", caption: "Pressure reverses in an angry cleansing hiss." },
  "clean-acceptance": { id: "clean-acceptance", caption: "The throat reopens and accepts the clean feed." },
  "tank-full": { id: "tank-full", caption: "Fuel chambers fill; the swallowing pulse slows." },
  "intake-seal": { id: "intake-seal", caption: "The slit closes and pressure equalizes." },
  "wound-brace": { id: "wound-brace", caption: "Armor tightens carefully around Renee's hand." },
  "repair-knocks": { id: "repair-knocks", caption: "Two answering knocks travel through the chassis." },
  "relaxed-idle": { id: "relaxed-idle", caption: "Ferravine's idle settles into a warm chord." },
});

export const RENEE_HUM_LOOPS = Object.freeze({
  calm: {
    id: "hum-calm",
    path: "./voice/renee/renee-hum-calm-candidate-v1.wav",
    caption: "Renee hums a low, even working phrase.",
  },
  concerned: {
    id: "hum-concerned",
    path: "./voice/renee/renee-hum-concerned-candidate-v1.wav",
    caption: "Renee's working hum tightens with concern.",
  },
  victorious: {
    id: "hum-victorious",
    path: "./voice/renee/renee-hum-victorious-candidate-v1.wav",
    caption: "Renee hums the two-tap phrase back to Ferravine.",
  },
});

export const CARE_SEQUENCE = Object.freeze([
  {
    id: "approach",
    title: "Approach the intake",
    instruction: "Let Renee announce her hands before the armor opens.",
    action: "OPEN THE INTAKE",
    reneeCue: "care-intake",
    bodyCues: ["intake-unfurl"],
    careFoley: "two-tap",
    hum: "calm",
    fuel: 0,
  },
  {
    id: "prepare",
    title: "Prepare the throat",
    instruction: "Test the seal and clear the feed collar.",
    action: "CHECK THE SEAL",
    reneeCue: null,
    bodyCues: ["throat-ready"],
    careFoley: "tools",
    hum: "calm",
    fuel: 0,
  },
  {
    id: "first-feed",
    title: "Offer the first mouthful",
    instruction: "Feed slowly enough for Ferravine to taste it.",
    action: "BEGIN CLEAN FUEL",
    reneeCue: "care-fuel",
    bodyCues: ["fuel-swallow", "taste-pause"],
    careFoley: "cloth",
    hum: "calm",
    fuel: 22,
  },
  {
    id: "contamination",
    title: "Catch the contamination",
    instruction: "The taste is wrong. Stop the feed before it reaches the warm organs.",
    action: "CLAMP AND PURGE",
    reneeCue: "care-contamination",
    bodyCues: ["contamination-clamp", "reverse-purge"],
    careFoley: "tools",
    hum: "concerned",
    fuel: 22,
  },
  {
    id: "refeed",
    title: "Refeed her cleanly",
    instruction: "Clear fuel only. Watch the swallowing pulse settle.",
    action: "REFEED SLOWLY",
    reneeCue: "care-full",
    bodyCues: ["clean-acceptance", "tank-full"],
    careFoley: "cloth",
    hum: "calm",
    fuel: 100,
  },
  {
    id: "seal",
    title: "Seal the intake",
    instruction: "Wipe the collar, close the slit, and listen for equal pressure.",
    action: "CLOSE AND LISTEN",
    reneeCue: null,
    bodyCues: ["intake-seal"],
    careFoley: "nails",
    hum: "calm",
    fuel: 100,
  },
  {
    id: "inspect",
    title: "Inspect the old wound",
    instruction: "Renee follows the scute seam until Ferravine shows where it hurts.",
    action: "TEST THE SCUTES",
    reneeCue: "care-damage",
    bodyCues: ["wound-brace"],
    careFoley: "nails",
    hum: "concerned",
    fuel: 100,
  },
  {
    id: "repair",
    title: "Close the wound",
    instruction: "Seat the patch without hiding the scar.",
    action: "SEAL THE WOUND",
    reneeCue: "repair",
    bodyCues: ["repair-knocks"],
    careFoley: "two-tap",
    hum: "victorious",
    fuel: 100,
  },
  {
    id: "depart",
    title: "Return to the road",
    instruction: "Ferravine is fed, sealed, and ready to carry the war party.",
    action: "DEPART",
    reneeCue: "combat-begins",
    bodyCues: ["relaxed-idle"],
    careFoley: "breath",
    hum: "victorious",
    fuel: 100,
  },
]);

export const CARE_AUDIO_POLICY = Object.freeze({
  bodyCueCount: Object.keys(FERRAVINE_CARE_CUES).length,
  hummingLoopCount: Object.keys(RENEE_HUM_LOOPS).length,
  twoTapMotif: true,
  scene: "Renee feeds and inspects Ferravine through the slit",
  bodyResponsesAreDesigned: true,
  hummingStatus: "accepted-by-drew-sequenced-only",
  mixPolicy: "voice, care Foley, body response, then optional hum; never simultaneous",
});
